version: '1'

services:
  # [dotnet/sdk]
  # build:でDockerfileが配置してあるPathを指定する。
  # container_name:で任意のコンテナ名を付けられる。無くても可。
  # depends_on:でコンテナの立ち上がる順番を指定。指定したサービスの後に立ち上がるようになる。
  # ports:ホスト側のポート:コンテナ側のポート
  # volumesでホスト側とコンテナ側のディレクトリを同期する場所を指定する.
  # dotnet:
  #   build: ./.docker/dotnet
  #   container_name: dotnet_container
  #   ports: 
  #     - "80:80"
  #   volumes: 
  #     - ./.docker/web/wwwroot:/var/wwwroot

  # #[postgresql]
  # # valume
  # db:
  #   build: ./.docker/db
  #   container_name: db_container
  #   env_file: .env
  #   ports: -"5432:5432"
  #   volumes:
  #     - postgresql-datavalume:/var/lib/postgresql/data

  #[nginx]
  web:
    build: ./.docker/web
    container_name: nginx_container
    ports: 
      - "8080:8080"



volumes:
  postgresql-datavalume:
